general:
  seed: 0
  logging_level: 0

hyperparams:
  lr: 0.001
  train_batch_size: 64
  val_batch_size: 64
  num_epochs: 50

dataset:
  name: "mnist"
  colored_percentage: 0.95  # Percentage of colored images in the MNIST dataset (the rest is white)